#!/bin/bash

# main function to run new deployment
delete::run() {
    echo "initializing vm deletion ..."

    # reading mandatory variables with values
    local vm_id=$(readopt -i --id)
    if [ -z "${vm_id}" ]; then
        echo "ERROR: vm deployment - No id provided with --id"
        exit 1
    fi

    # get vm name and count
    local prx_name=$(ssh prx "qm config $vm_id | grep '^name:' | sed 's/name: //'")
    local prx_depl=$(ssh prx "qm config $vm_id | grep '^name:' | sed 's/name: //' | sed 's/[0-9]*$//'")
    local vm_count=$(ssh prx "qm config $vm_id | grep '^name:' | awk -F '[^0-9]+' '{print $NF}'")
    local terraform_dir="/home/j4s/auto/terraform/"

    # execute function for deletion in different env's
    rm_prox
    rm_ansible
    rm_dns
    terraform_refresh

    echo "deletion of vm done"
}

# description for help
delete::description() {
    echo "Delete one or more proxmox vms"
}

# usage of command for help 
delete::usage() {
    cat <<EOT
    -i --id <system id>                    ID of the vm to be deleted
EOT
}

# delete proxmox vm
rm_prox() {
    # connect to proxmox
    # stop and delete vm with provided id
    ssh prx << EOF
        qm stop $vm_id
        qm destroy $vm_id
EOF
}

# delete ansible config
rm_ansible() {
    # delete vm ip from hosts file
    sed -i "/10\.10\.21\.$vm_count/d" /etc/ansible/hosts
}

# delete bind9 dns config
# delete line with vm ip
rm_dns() {
    ssh raspi << EOF
    sed -i "/10\.10\.21\.$vm_count/d" /bind9/config/db.caesarlab.cc
    cd /bind9
    docker-compose restart
EOF
}

# refresh state file from terraform
terraform_refresh() {
    
    cd $terraform_dir
    #terraform workspace select $prx_depl
    terraform state rm "proxmox_vm_qemu.j4s_template[${vm_count -1}]"
    terraform plan
    terraform apply
}