#!/bin/bash

update::run() {
    echo "upgrading systems ..."
    ansible-playbook --ssh-extra-args='-o StrictHostKeyChecking=no' -i /tmp/new_hosts /home/j4s/auto/ansible/ansible/vm_update_ansible.yml
    echo "upgrades done"

}

update::description() {
    echo "Upgrade all available vms "
}

update::usage() {
    cat <<EOT
    -h                   For additional help ;)  
EOT
}